export {
    login,
    sendShallWe,
    increaseLike,
    getComments,
    getUserPage,
    createPost,
    getChatRoomList,
    createChatRoom,
    joinChatRoom,
    exitChatRoom,
    getTagList,
    getUserList,
    addTag,
    followUser,
    applySetting,
    getGridPost,
    putPost,
    deletePost,
} from './user';