# Generated by Django 3.1.2 on 2020-10-29 18:17

from django.db import migrations, models
import shallWeGame.managers


class Migration(migrations.Migration):

    dependencies = [
        ('shallWeGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', shallWeGame.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
